name: Terraform Deployment to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Allows reading repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login (OIDC Authentication)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true  # Prevents login failure if no subscriptions are assigned

      - name: Verify Azure Login
        run: az account show

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Plan Terraform Deployment
        run: terraform plan -out=tfplan
        continue-on-error: false  # Fails the workflow if the plan has issues

      - name: Show Terraform Plan Output
        run: terraform show -json tfplan | jq '.'  # Helps in debugging by showing the plan output

      - name: Apply Terraform Deployment
        run: terraform apply -auto-approve tfplan
        continue-on-error: false  # Ensures the deployment does not continue if there are errors

      - name: Terraform Output
        run: terraform output
